name = "ATM 10 Custom"
author = "flashgnash"
version = "8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67234e16bf1d1a0c3316fb0a61f596e55ca09fc45cb8bf79fe42719bc4be0ce7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
