name = "ATM 10 Custom"
author = "flashgnash"
version = "8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0c1bdcea944037219f6b3e6fc68029d80dd934f4b861ef1d45166712f9e262b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
